// Interfaces for WordPress user data structures

export interface CliOptions {
  dryRun: boolean;
  force: boolean;
  json: boolean;
  path: string;
  verbose: boolean;
}

export interface WordPressUser {
  id: number;
  login: string;
  email: string;
  displayName: string;
  roles: string[];
  registeredDate?: string;
  lastLoginDate?: string;
  userStatus?: string;
}

export interface UserIssue {
  user: WordPressUser;
  type: 'default_admin' | 'admin_default_email' | 'multiple_admins' | 'suspicious_login' | 'weak_role_assignment' | 'inactive_user' | 'disposable_email' | 'spam_email' | 'no_role' | 'deleted_status';
  severity: 'HIGH' | 'MEDIUM' | 'LOW';
  description: string;
  recommendation: string;
}

export interface UsersCheckResult {
  path: string;
  usersFound: boolean;
  source: 'database' | 'wp-users.php' | 'sql-export' | 'none';
  users: WordPressUser[];
  issues: UserIssue[];
  hasIssues: boolean;
  bySeverity: Record<string, number>;
  summary: {
    total: number;
    administrators: number;
    editors: number;
    authors: number;
    contributors: number;
    subscribers: number;
    inactiveOver90Days: number;
    disposableEmails: number;
    suspiciousLogins: number;
  };
}

// Constants for user detection

export const DEFAULT_ADMIN_LOGIN = 'admin';
export const DEFAULT_ADMIN_EMAIL = 'admin@example.com';

// Disposable email domains that should be flagged
export const DISPOSABLE_EMAIL_DOMAINS = [
  '10minutemail.com', '33mail.com', 'anonbox.net', 'anonymbox.com',
  'binkmail.com', 'bobmail.info', 'boftom.com', 'bsnow.net',
  'bugmenot.com', 'bumpymail.com', 'casualdx.com', 'cool.fr.nf',
  'correo.blogos.net', 'cosmorph.com', 'courriel.fr.nf', 'courrieltemporaire.com',
  'curryworld.de', 'cust.in', 'dacoolest.com', 'dandikmail.com',
  'deadaddress.com', 'despam.it', 'devnullmail.com', 'dfgh.net',
  'digitalsanctuary.com', 'discard.email', 'disposable.com', 'disposableaddress.com',
  'disposableemailaddresses.com', 'disposableinbox.com', 'dispose.it', 'dispostable.com',
  'dodgeit.com', 'dodgemail.de', 'dodgit.org', 'dodgitemail.com',
  'dontreg.com', 'dontsendmespam.de', 'dump-email.info', 'dumpandjunk.com',
  'dumpmail.de', 'dumpyemail.com', 'e4ward.com', 'email60.com',
  'emaildienst.de', 'emailgo.de', 'emailias.com', 'emailinfuture.com',
  'emaillime.com', 'emailmiser.com', 'emailsensei.com', 'emailtemporanea.com',
  'emailtemporanea.net', 'emailtemporar.ro', 'emailtemporario.com.br', 'emailthe.net',
  'emailtmp.com', 'emailwarden.com', 'emailx.at.hm', 'emailxfer.com',
  'emz.net', 'enterto.com', 'ephemail.net', 'ero-tube.org',
  'evopo.com', 'explodemail.com', 'fakeinbox.com', 'fakeinformation.com',
  'fansworldwide.de', 'fastacura.com', 'fastchevy.com', 'fastchrysler.com',
  'fastkawasaki.com', 'fastmazda.com', 'fastmitsubishi.com', 'fastnissan.com',
  'fastsubaru.com', 'fastsuzuki.com', 'fasttoyota.com', 'fastyamaha.com',
  'filzmail.com', 'fivemail.de', 'fixmail.tk', 'fizmail.com',
  'frapmail.com', 'friendlymail.co.uk', 'front14.org', 'fux0ringduh.com',
  'garliclife.com', 'gehensiull.com', 'get1mail.com', 'get2mail.fr',
  'getairmail.com', 'getmails.eu', 'getnada.com', 'getonemail.com',
  'getonemail.net', 'ghosttexter.de', 'gishpuppy.com', 'goemailgo.com',
  'gorillaswithdirtyarmpits.com', 'gowikibooks.com', 'gowikicampus.com', 'gowikicars.com',
  'gowikifilms.com', 'gowikigames.com', 'gowikimusic.com', 'gowikinetwork.com',
  'gowikitravel.com', 'gowikitv.com', 'great-host.in', 'greensloth.com',
  'grr.la', 'gsrv.ru', 'guerillamail.biz', 'guerrillamailblock.com',
  'guerrillamail.com', 'guerrillamail.de', 'guerrillamail.info', 'guerrillamail.net',
  'guerrillamail.org', 'guerrillapv.com', 'guerrillawild.com', 'haltospam.com',
  'hatespam.org', 'hidemail.de', 'hidzz.com', 'hochsitze.com',
  'hopemail.biz', 'hotpop.com', 'hulapla.de', 'ieatspam.eu',
  'ieatspam.info', 'ieh-mail.de', 'ihateyoualot.info', 'iheartspam.org',
  'imails.info', 'imgof.com', 'imgv.de', 'imstations.com',
  'inbax.tk', 'inbox.si', 'inboxalias.com', 'inboxclean.com',
  'inboxclean.org', 'incognitomail.com', 'incognitomail.net', 'incognitomail.org',
  'insorg-mail.info', 'instant-mail.de', 'instantemailaddress.com', 'ipoo.org',
  'irish2me.com', 'iwi.net', 'jetable.com', 'jetable.fr.nf',
  'jetable.net', 'jetable.org', 'jnxjn.com', 'jourrapide.com',
  'jsrsolutions.com', 'kasmail.com', 'kaspop.com', 'keepmymail.com',
  'killmail.com', 'killmail.net', 'kimsdisk.com', 'kingsq.ga',
  'kiois.com', 'kir.ch.tc', 'klassmaster.com', 'klassmaster.net',
  'klzlv.com', 'kook.ml', 'kulturbetrieb.info', 'kurzepost.de',
  'lawlita.com', 'letthemeatspam.com', 'lhsdv.com', 'lifebyfood.com',
  'link2mail.net', 'litedrop.com', 'loadby.us', 'login-email.ml',
  'lol.ovpn.to', 'lookugly.com', 'lopl.co.cc', 'lortemail.dk',
  'lovemeleaveme.com', 'lr78.com', 'lroid.com', 'lukop.dk',
  'm4ilweb.info', 'maboard.com', 'mail-hierarchie.net', 'mail-temporaire.fr',
  'mail.by', 'mail.mezimages.net', 'mail114.net', 'mail2rss.org',
  'mail333.com', 'mail4trash.com', 'mailbidon.com', 'mailblocks.com',
  'mailbucket.org', 'mailcat.biz', 'mailcatch.com', 'mailde.de',
  'mailde.info', 'maildrop.cc', 'maildrop.cf', 'maildrop.ga',
  'maildrop.gq', 'maildrop.ml', 'maildu.de', 'maildx.com',
  'mailed.ro', 'maileater.com', 'mailexpire.com', 'mailfa.tk',
  'mailforspam.com', 'mailfree.ga', 'mailfree.gq', 'mailfree.ml',
  'mailfreeonline.com', 'mailguard.me', 'mailhazard.com', 'mailhazard.us',
  'mailhz.me', 'mailimate.com', 'mailin8r.com', 'mailinater.com',
  'mailincubator.com', 'mailismagic.com', 'mailjunk.cf', 'mailjunk.ga',
  'mailjunk.gq', 'mailjunk.ml', 'mailjunk.tk', 'mailmate.com',
  'mailme.gq', 'mailme.ir', 'mailme.lv', 'mailme24.com',
  'mailmetrash.com', 'mailmoat.com', 'mailnator.com', 'mailnesia.com',
  'mailnull.com', 'mailorg.org', 'mailpick.biz', 'mailproxsy.com',
  'mailquack.com', 'mailrock.biz', 'mailscrap.com', 'mailseal.de',
  'mailshell.com', 'mailsiphon.com', 'mailslapping.com', 'mailslite.com',
  'mailtemp.info', 'mailtome.de', 'mailtothis.com', 'mailtrash.net',
  'mailtv.net', 'mailtv.tv', 'mailzi.ru', 'mailzilla.com',
  'mailzilla.org', 'makemetheking.com', 'manifestgenerator.com', 'manybrain.com',
  'mbx.cc', 'mega.zik.dj', 'meinspamschutz.de', 'meltmail.com',
  'messagebeamer.de', 'mezimages.net', 'mierdamail.com', 'migmail.pl',
  'migumail.com', 'mintemail.com', 'mjukgansen.nu', 'moakt.com',
  'mobi.web.id', 'mobileninja.co.uk', 'moburl.com', 'mohmal.com',
  'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf', 'monumentmail.com',
  'ms9.mailslite.com', 'msa.minsmail.com', 'msb.minsmail.com', 'mspeciosa.com',
  'mswork.ru', 'mt2009.com', 'mt2014.com', 'myalias.pw', 'mycleaninbox.net',
  'myemailboxy.com', 'mymail-in.net', 'mymailoasis.com', 'mynetstore.de',
  'mypacks.net', 'mypartyclip.de', 'myphantomemail.com', 'myspaceinc.com',
  'myspaceinc.net', 'myspacepimpedup.com', 'mytempemail.com', 'mytempmail.com',
  'mytrashmail.com', 'neomailbox.com', 'nepwk.com', 'nervmich.net',
  'nervtmansen.nl', 'netmails.com', 'netmails.net', 'netzidiot.de',
  'neverbox.com', 'no-spam.ws', 'nobulk.com', 'noclickemail.com',
  'nogmailspam.info', 'nomail.pw', 'nomail.xl.cx', 'nomail2me.com',
  'nomorespamemails.com', 'nonspam.eu', 'nonspammer.de', 'noref.in',
  'nospam.ze.tc', 'nospam4.us', 'nospamfor.us', 'nospammail.net',
  'nospamthanks.info', 'notmailinator.com', 'notsharingmy.info', 'nowhere.org',
  'nowmymail.com', 'ntlhelp.net', 'nurfuerspam.de', 'nus.edu.sg',
  'nwldx.com', 'objectmail.com', 'obobbo.com', 'odnorazovoe.ru',
  'oneoffemail.com', 'onewaymail.com', 'onlatedotcom.info', 'online.ms',
  'oopi.org', 'opayq.com', 'ordinaryamerican.net', 'otherinbox.com',
  'ourklips.com', 'outlawspam.com', 'ovpn.to', 'owlpic.com',
  'pancakemail.com', 'pjjkp.com', 'plexolan.de', 'poczta.onet.pl',
  'politikerclub.de', 'poofy.org', 'pookmail.com', 'privacy.net',
  'privatdemail.net', 'privy-mail.com', 'privymail.de', 'proxymail.eu',
  'prtnx.com', 'punkass.com', 'putthisinyourspamdatabase.com', 'qq.com',
  'quickinbox.com', 'quickmail.nl', 'rainmail.biz', 'rcpt.at',
  'reallymymail.com', 'realtyalerts.ca', 'recode.me', 'recursor.net',
  'recyclemail.dk', 'regbypass.com', 'regbypass.comsafe-mail.net', 'rejectmail.com',
  'remail.cf', 'remail.ga', 'rhyta.com', 'rklips.com',
  'rmqkr.net', 'royal.net', 'rppkn.com', 'rtrtr.com',
  's0ny.net', 'safe-mail.net', 'safersignup.de', 'safetymail.info',
  'safetypost.de', 'sandelf.de', 'saynotospams.com', 'schafmail.de',
  'schrott-email.de', 'secretemail.de', 'selfdestructingmail.com', 'sendspamhere.com',
  'senseless-entertainment.com', 'server.ms.selfip.net', 'sharklasers.com', 'shieldemail.com',
  'shiftmail.com', 'shitmail.me', 'shortmail.net', 'shut.name',
  'shut.ws', 'sibmail.com', 'sinnlos-mail.de', 'siteposter.net',
  'skeefmail.com', 'slaskpost.se', 'slopsbox.com', 'slowslow.de',
  'smashmail.de', 'smellfear.com', 'snakemail.com', 'sneakemail.com',
  'snkmail.com', 'sofimail.com', 'sofort-mail.de', 'softpls.asia',
  'sogetthis.com', 'soisz.com', 'solvemail.info', 'soodonims.com',
  'spam.la', 'spam.su', 'spam4.me', 'spamail.de', 'spamarrest.com',
  'spamavert.com', 'spambob.com', 'spambob.net', 'spambob.org',
  'spambog.com', 'spambog.de', 'spambog.ru', 'spambox.info',
  'spambox.irishspringrealty.com', 'spambox.us', 'spamcannon.com', 'spamcannon.net',
  'spamcero.com', 'spamcon.org', 'spamcorptastic.com', 'spamcowboy.com',
  'spamcowboy.net', 'spamcowboy.org', 'spamday.com', 'spamdecoy.net',
  'spamex.com', 'spamfighter.cf', 'spamfighter.ga', 'spamfighter.gq',
  'spamfighter.ml', 'spamfighter.tk', 'spamfree24.com', 'spamfree24.de',
  'spamfree24.eu', 'spamfree24.info', 'spamfree24.net', 'spamfree24.org',
  'spamgoes.in', 'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org',
  'spamherelots.com', 'spamhereplease.com', 'spamhole.com', 'spamify.com',
  'spaminator.de', 'spaminator.us', 'spamkill.info', 'spaml.com',
  'spaml.de', 'spamoff.de', 'spamsalad.in', 'spamslicer.com',
  'spamspot.com', 'spamstack.net', 'spamthis.co.uk', 'spamthisplease.com',
  'spamtrail.com', 'spamtroll.net', 'speed.1s.fr', 'spoofmail.de',
  'squizzy.de', 'ssoia.com', 'startkeys.com', 'stexsy.com',
  'stinkefinger.net', 'stop-my-spam.cf', 'stop-my-spam.com', 'stop-my-spam.ga',
  'stop-my-spam.ml', 'stop-my-spam.tk', 'streetwisemail.com', 'stuffmail.de',
  'super-auswahl.de', 'supergreatmail.com', 'supermailer.jp', 'superrito.com',
  'superstachel.de', 'suremail.info', 'svk.jp', 'sweetxxx.de',
  'tagyourself.com', 'talkinator.com', 'tapchicuoihoi.com', 'techemail.com',
  'teewars.org', 'teleosaurs.xyz', 'teleworm.com', 'teleworm.us',
  'temp-mail.org', 'temp-mail.ru', 'temp.head.com', 'tempail.com',
  'tempalias.com', 'tempe-mail.com', 'temped.com', 'tempemail.biz',
  'tempemail.co.za', 'tempemail.com', 'tempemail.net', 'tempinbox.co.uk',
  'tempinbox.com', 'tempmail.co', 'tempmail.de', 'tempmail.eu',
  'tempmail.it', 'tempmail.net', 'tempmail.us', 'tempmailaddress.com',
  'tempmailer.com', 'tempmailer.de', 'tempomail.fr', 'temporarily.de',
  'temporario.com.br', 'temporaryemail.net', 'temporaryforwarding.com', 'temporaryinbox.com',
  'temporarymailaddress.com', 'tempsky.com', 'temptation.to', 'tempymail.com',
  'thanksnospam.info', 'thankyou2010.com', 'thc.st', 'thelimestones.com',
  'thietbivanphong4g.com', 'thisisnotmyrealemail.com', 'thismail.net', 'thismail.ru',
  'throam.com', 'throwam.com', 'throwaway.email', 'throwawaymail.com',
  'tilien.com', 'tittbit.in', 'tmailinator.com', 'tmail.ws',
  'tmpeml.info', 'toiea.com', 'tokenmail.de', 'toomail.biz',
  'topranklist.de', 'tradermail.info', 'trash-amila.com', 'trash-mail.at',
  'trash-mail.com', 'trash-mail.de', 'trash2009.com', 'trashemail.de',
  'trashmail.at', 'trashmail.com', 'trashmail.de', 'trashmail.me',
  'trashmail.net', 'trashmail.org', 'trashmail.ws', 'trashmailer.com',
  'trashymail.com', 'trashymail.net', 'trbvm.com', 'trickmail.net',
  'trillianpro.com', 'tryalert.com', 'turual.com', 'twinmail.de',
  'twoweirdtricks.com', 'tyldd.com', 'uggsrock.com', 'upliftnow.com',
  'uplipht.com', 'uroid.com', 'us.af', 'valemail.net', 'venompen.com',
  'veryrealemail.com', 'viditag.com', 'viewcastmedia.com', 'viewcastmedia.net',
  'viewcastmedia.org', 'viralplays.com', 'vkcode.ru', 'vpn.st',
  'vsimcard.com', 'vubby.com', 'wasteland.rfc822.org', 'webemail.me',
  'webm4il.info', 'webuser.in', 'wee.my', 'weg-werf-email.de',
  'wegwerf-email-addressen.de', 'wegwerf-emails.de', 'wegwerfadresse.de', 'wegwerfemail.com',
  'wegwerfemail.de', 'wegwerfmail.de', 'wegwerfmail.info', 'wegwerfmail.net',
  'wegwerfmail.org', 'wetrainbayarea.com', 'wetrainbayarea.org', 'wh4f.org',
  'whatiaas.com', 'whatpaas.com', 'whopy.com', 'whtjddn.33mail.com',
  'whyspam.me', 'willhackforfood.biz', 'willselfdestruct.com', 'winemaven.info',
  'wolfsmail.tk', 'writeme.us', 'wronghead.com', 'wuzup.net',
  'wuzupmail.net', 'wwwnew.eu', 'xagloo.com', 'xemaps.com',
  'xents.com', 'xmaily.com', 'xn--9kq967o.com', 'xoxy.net',
  'yapped.net', 'yeah.net', 'yep.it', 'yogamaven.com', 'yopmail.com',
  'yopmail.fr', 'yopmail.gold', 'yopmail.net', 'yordanmail.cf',
  'you-spam.com', 'yourdomain.com', 'ypmail.webarnak.fr.eu.org', 'yuurok.com',
  'z1p.biz', 'za.com', 'zehnminuten.de', 'zehnminutenmail.de',
  'zippymail.info', 'zoaxe.com', 'zoemail.com', 'zoemail.net',
  'zoemail.org', 'zomg.info', 'zxcv.com', 'zxcvbnm.com',
  'zzz.com'
];

// Known spam/malicious email domains
export const SPAM_EMAIL_DOMAINS = [
  '007 mil.com', '0x00.name', '1pad.de', '1saltillo.com', '20mail.it',
  '21cn.com', '2prong.com', '2wheat.com', '3-a.net', '4n4nym0u5.com',
  '4warding.com', '4warding.net', '4warding.org', '510-pen.tv', '5starbiz.com',
  '60minutemail.com', '675hosting.com', '675hosting.net', '675hosting.org', '6url.com',
  '75hg.com', '7tags.com', '90pack.com', 'a-bc.net', 'afrobacon.com',
  'agedmail.com', 'ajaxapp.net', 'amilegit.com', 'amiri.net', 'amirinetllc.com',
  'amongthieves.com', 'anonbox.net', 'anonmails.de', 'anonymbox.com', 'antichef.com',
  'antichef.net', 'antireg.ru', 'antispam.de', 'antispam24.pl', 'antispammail.de',
  'armyspy.com', 'azmeil.tk', 'baxomale.hmt.ce', 'beefmilk.com', 'bigstring.com',
  'binkmail.com', 'bio-muesli.info', 'bio-muesli.net', 'blackmarkettech.org', 'bladesmail.net',
  'bloatbox.com', 'bobmail.info', 'bodhi.lawlita.com', 'boftom.com', 'bootybay.de',
  'boun.cr', 'bouncr.com', 'breakthru.com', 'brefmail.com', 'brennendesreich.de',
  'broadbandninja.com', 'bsnow.net', 'bspamfree.org', 'buffemail.com', 'bugmenot.com',
  'bumpymail.com', 'bund.us', 'burstmail.de', 'buymoreplays.com', 'byom.de',
  'c2.hu', 'card.zp.ua', 'casualdx.com', 'cek.pm', 'cellurl.com',
  'centermail.com', 'centermail.net', 'cheatmail.de', 'childsavetrust.org', 'chogmail.com',
  'choicemail1.com', 'clixser.com', 'cmail.com', 'cmail.net', 'cmail.org',
  'coldemail.info', 'consumerriot.com', 'cool.fr.nf', 'correo.blogos.net', 'cosmorph.com',
  'courriel.fr.nf', 'courrieltemporaire.com', 'cubiclink.com', 'curryworld.de', 'cust.in',
  'cuvox.de', 'd3p.dk', 'dacoolest.com', 'dandikmail.com', 'dayrep.com',
  'dcemail.com', 'deadaddress.com', 'deadfake.cf', 'deadfake.ga', 'deadfake.gq',
  'deadfake.ml', 'deadfake.tk', 'deadspam.com', 'delikkt.de', 'despam.it',
  'despammed.com', 'devnullmail.com', 'dfgh.net', 'digitalsanctuary.com', 'dingbone.com',
  'discard.cf', 'discard.email', 'discard.ga', 'discard.gq', 'discard.ml',
  'discard.tk', 'disposable.com', 'disposableaddress.com', 'disposableemailaddresses.com',
  'disposableinbox.com', 'dispose.it', 'disposeamail.com', 'disposemail.com', 'dispostable.com',
  'dm.w3internet.co.uk', 'dodgeit.com', 'dodgemail.de', 'dodgit.com', 'dodgit.org',
  'dodgitemail.com', 'dodsi.com', 'dontreg.com', 'dontsendmespam.de', 'drdrb.com',
  'dump-and-junk.com', 'dump-email.info', 'dumpandjunk.com', 'dumpmail.com', 'dumpmail.de',
  'dumpyemail.com', 'e-mail.com', 'e-mail.org', 'e4ward.com', 'easytrashmail.com',
  'einmalmail.de', 'email60.com', 'emailage.cf', 'emailage.ga', 'emailage.gq',
  'emailage.ml', 'emailage.tk', 'emaildienst.de', 'emailgo.de', 'emailias.com',
  'emailinfuture.com', 'emaillime.com', 'emailmiser.com', 'emailsensei.com', 'emailtemporanea.com',
  'emailtemporanea.net', 'emailtemporar.ro', 'emailtemporario.com.br', 'emailthe.net', 'emailtmp.com',
  'emailto.de', 'emailwarden.com', 'emailx.at.hm', 'emailxfer.com', 'emz.net',
  'enterto.com', 'ephemail.net', 'ero-tube.org', 'etranquil.com', 'etranquil.net',
  'etranquil.org', 'evopo.com', 'explodemail.com', 'fakeinbox.com', 'fakeinformation.com',
  'fansworldwide.de', 'fastacura.com', 'fastchevy.com', 'fastchrysler.com', 'fastkawasaki.com',
  'fastmazda.com', 'fastmitsubishi.com', 'fastnissan.com', 'fastsubaru.com', 'fastsuzuki.com',
  'fasttoyota.com', 'fastyamaha.com', 'filzmail.com', 'fivemail.de', 'fixmail.tk',
  'fizmail.com', 'fr33mail.info', 'frapmail.com', 'friendlymail.co.uk', 'front14.org',
  'fux0ringduh.com', 'garliclife.com', 'gehensiull.com', 'get1mail.com', 'get2mail.fr',
  'getairmail.com', 'getmails.eu', 'getnada.com', 'getonemail.com', 'getonemail.net',
  'ghosttexter.de', 'gishpuppy.com', 'goemailgo.com', 'gorillaswithdirtyarmpits.com', 'gowikibooks.com',
  'gowikicampus.com', 'gowikicars.com', 'gowikifilms.com', 'gowikigames.com', 'gowikimusic.com',
  'gowikinetwork.com', 'gowikitravel.com', 'gowikitv.com', 'great-host.in', 'greensloth.com',
  'grr.la', 'gsrv.ru', 'guerillamail.biz', 'guerrillamailblock.com', 'guerrillamail.com',
  'guerrillamail.de', 'guerrillamail.info', 'guerrillamail.net', 'guerrillamail.org', 'guerrillapv.com',
  'guerrillawild.com', 'haltospam.com', 'hatespam.org', 'hidemail.de', 'hidzz.com',
  'hochsitze.com', 'hopemail.biz', 'hotpop.com', 'hulapla.de', 'ieatspam.eu',
  'ieatspam.info', 'ieh-mail.de', 'ihateyoualot.info', 'iheartspam.org', 'imails.info',
  'imgof.com', 'imgv.de', 'imstations.com', 'inbax.tk', 'inbox.si',
  'inboxalias.com', 'inboxclean.com', 'inboxclean.org', 'incognitomail.com', 'incognitomail.net',
  'incognitomail.org', 'infocom.zp.ua', 'insorg-mail.info', 'instant-mail.de', 'instantemailaddress.com',
  'instantmail.us', 'ipoo.org', 'irish2me.com', 'iwi.net', 'jetable.com',
  'jetable.fr.nf', 'jetable.net', 'jetable.org', 'jnxjn.com', 'jourrapide.com',
  'jsrsolutions.com', 'kasmail.com', 'kaspop.com', 'keepmymail.com', 'killmail.com',
  'killmail.net', 'kimsdisk.com', 'kingsq.ga', 'kiois.com', 'kir.ch.tc',
  'klassmaster.com', 'klassmaster.net', 'klzlv.com', 'kook.ml', 'kulturbetrieb.info',
  'kurzepost.de', 'lawlita.com', 'letthemeatspam.com', 'lhsdv.com', 'lifebyfood.com',
  'link2mail.net', 'litedrop.com', 'loadby.us', 'login-email.ml', 'lol.ovpn.to',
  'lookugly.com', 'lopl.co.cc', 'lortemail.dk', 'lovemeleaveme.com', 'lr78.com',
  'lroid.com', 'lukop.dk', 'm4ilweb.info', 'maboard.com', 'mail-hierarchie.net',
  'mail-temporaire.fr', 'mail.by', 'mail.mezimages.net', 'mail.zp.ua', 'mail114.net',
  'mail2rss.org', 'mail333.com', 'mail4trash.com', 'mailbidon.com', 'mailblocks.com',
  'mailbucket.org', 'mailcat.biz', 'mailcatch.com', 'mailde.de', 'mailde.info',
  'maildrop.cc', 'maildrop.cf', 'maildrop.ga', 'maildrop.gq', 'maildrop.ml',
  'maildu.de', 'maildx.com', 'mailed.ro', 'maileater.com', 'mailexpire.com',
  'mailfa.tk', 'mailforspam.com', 'mailfree.ga', 'mailfree.gq', 'mailfree.ml',
  'mailfreeonline.com', 'mailguard.me', 'mailhazard.com', 'mailhazard.us', 'mailhz.me',
  'mailimate.com', 'mailin8r.com', 'mailinater.com', 'mailincubator.com', 'mailismagic.com',
  'mailjunk.cf', 'mailjunk.ga', 'mailjunk.gq', 'mailjunk.ml', 'mailjunk.tk',
  'mailmate.com', 'mailme.gq', 'mailme.ir', 'mailme.lv', 'mailme24.com',
  'mailmetrash.com', 'mailmoat.com', 'mailnator.com', 'mailnesia.com', 'mailnull.com',
  'mailorg.org', 'mailpick.biz', 'mailproxsy.com', 'mailquack.com', 'mailrock.biz',
  'mailscrap.com', 'mailseal.de', 'mailshell.com', 'mailsiphon.com', 'mailslapping.com',
  'mailslite.com', 'mailtemp.info', 'mailtome.de', 'mailtothis.com', 'mailtrash.net',
  'mailtv.net', 'mailtv.tv', 'mailzi.ru', 'mailzilla.com', 'mailzilla.org',
  'makemetheking.com', 'manifestgenerator.com', 'manybrain.com', 'mbx.cc', 'mega.zik.dj',
  'meinspamschutz.de', 'meltmail.com', 'messagebeamer.de', 'mezimages.net', 'mierdamail.com',
  'migmail.pl', 'migumail.com', 'mintemail.com', 'mjukgansen.nu', 'moakt.com',
  'mobi.web.id', 'mobileninja.co.uk', 'moburl.com', 'mohmal.com', 'moncourrier.fr.nf',
  'monemail.fr.nf', 'monmail.fr.nf', 'monumentmail.com', 'ms9.mailslite.com', 'msa.minsmail.com',
  'msb.minsmail.com', 'mspeciosa.com', 'mswork.ru', 'mt2009.com', 'mt2014.com',
  'myalias.pw', 'mycleaninbox.net', 'myemailboxy.com', 'mymail-in.net', 'mymailoasis.com',
  'mynetstore.de', 'mypacks.net', 'mypartyclip.de', 'myphantomemail.com', 'myspaceinc.com',
  'myspaceinc.net', 'myspacepimpedup.com', 'mytempemail.com', 'mytempmail.com', 'mytrashmail.com',
  'neomailbox.com', 'nepwk.com', 'nervmich.net', 'nervtmansen.nl', 'netmails.com',
  'netmails.net', 'netzidiot.de', 'neverbox.com', 'no-spam.ws', 'nobulk.com',
  'noclickemail.com', 'nogmailspam.info', 'nomail.pw', 'nomail.xl.cx', 'nomail2me.com',
  'nomorespamemails.com', 'nonspam.eu', 'nonspammer.de', 'noref.in', 'nospam.ze.tc',
  'nospam4.us', 'nospamfor.us', 'nospammail.net', 'nospamthanks.info', 'notmailinator.com',
  'notsharingmy.info', 'nowhere.org', 'nowmymail.com', 'ntlhelp.net', 'nurfuerspam.de',
  'nus.edu.sg', 'nwldx.com', 'objectmail.com', 'obobbo.com', 'odnorazovoe.ru',
  'oneoffemail.com', 'onewaymail.com', 'onlatedotcom.info', 'online.ms', 'oopi.org',
  'opayq.com', 'ordinaryamerican.net', 'otherinbox.com', 'ourklips.com', 'outlawspam.com',
  'ovpn.to', 'owlpic.com', 'pancakemail.com', 'pjjkp.com', 'plexolan.de',
  'politikerclub.de', 'poofy.org', 'pookmail.com', 'privacy.net', 'privatdemail.net',
  'privy-mail.com', 'privymail.de', 'proxymail.eu', 'prtnx.com', 'punkass.com',
  'putthisinyourspamdatabase.com', 'qq.com', 'quickinbox.com', 'quickmail.nl', 'rainmail.biz',
  'rcpt.at', 'reallymymail.com', 'realtyalerts.ca', 'recode.me', 'recursor.net',
  'recyclemail.dk', 'regbypass.com', 'regbypass.comsafe-mail.net', 'rejectmail.com', 'remail.cf',
  'remail.ga', 'rhyta.com', 'rklips.com', 'rmqkr.net', 'royal.net',
  'rppkn.com', 'rtrtr.com', 's0ny.net', 'safe-mail.net', 'safersignup.de',
  'safetymail.info', 'safetypost.de', 'sandelf.de', 'saynotospams.com', 'schafmail.de',
  'schrott-email.de', 'secretemail.de', 'selfdestructingmail.com', 'sendspamhere.com', 'senseless-entertainment.com',
  'server.ms.selfip.net', 'sharklasers.com', 'shieldemail.com', 'shiftmail.com', 'shitmail.me',
  'shortmail.net', 'shut.name', 'shut.ws', 'sibmail.com', 'sinnlos-mail.de',
  'siteposter.net', 'skeefmail.com', 'slaskpost.se', 'slopsbox.com', 'slowslow.de',
  'smashmail.de', 'smellfear.com', 'snakemail.com', 'sneakemail.com', 'snkmail.com',
  'sofimail.com', 'sofort-mail.de', 'softpls.asia', 'sogetthis.com', 'soisz.com',
  'solvemail.info', 'soodonims.com', 'spam.la', 'spam.su', 'spam4.me',
  'spamarrest.com', 'spamavert.com', 'spambob.com', 'spambob.net', 'spambob.org',
  'spambog.com', 'spambog.de', 'spambog.ru', 'spambox.info', 'spambox.irishspringrealty.com',
  'spambox.us', 'spamcannon.com', 'spamcannon.net', 'spamcero.com', 'spamcon.org',
  'spamcorptastic.com', 'spamcowboy.com', 'spamcowboy.net', 'spamcowboy.org', 'spamday.com',
  'spamdecoy.net', 'spamex.com', 'spamfighter.cf', 'spamfighter.ga', 'spamfighter.gq',
  'spamfighter.ml', 'spamfighter.tk', 'spamfree24.com', 'spamfree24.de', 'spamfree24.eu',
  'spamfree24.info', 'spamfree24.net', 'spamfree24.org', 'spamgoes.in', 'spamgourmet.com',
  'spamgourmet.net', 'spamgourmet.org', 'spamherelots.com', 'spamhereplease.com', 'spamhole.com',
  'spamify.com', 'spaminator.de', 'spaminator.us', 'spamkill.info', 'spaml.com',
  'spaml.de', 'spamoff.de', 'spamsalad.in', 'spamslicer.com', 'spamspot.com',
  'spamstack.net', 'spamthis.co.uk', 'spamthisplease.com', 'spamtrail.com', 'spamtroll.net',
  'speed.1s.fr', 'spoofmail.de', 'squizzy.de', 'ssoia.com', 'startkeys.com',
  'stexsy.com', 'stinkefinger.net', 'stop-my-spam.cf', 'stop-my-spam.com', 'stop-my-spam.ga',
  'stop-my-spam.ml', 'stop-my-spam.tk', 'streetwisemail.com', 'stuffmail.de', 'super-auswahl.de',
  'supergreatmail.com', 'supermailer.jp', 'superrito.com', 'superstachel.de', 'suremail.info',
  'svk.jp', 'sweetxxx.de', 'tagyourself.com', 'talkinator.com', 'tapchicuoihoi.com',
  'techemail.com', 'teewars.org', 'teleosaurs.xyz', 'teleworm.com', 'teleworm.us',
  'temp-mail.org', 'temp-mail.ru', 'temp.head.com', 'tempail.com', 'tempalias.com',
  'tempe-mail.com', 'temped.com', 'tempemail.biz', 'tempemail.co.za', 'tempemail.com',
  'tempemail.net', 'tempinbox.co.uk', 'tempinbox.com', 'tempmail.co', 'tempmail.de',
  'tempmail.eu', 'tempmail.it', 'tempmail.net', 'tempmail.us', 'tempmailaddress.com',
  'tempmailer.com', 'tempmailer.de', 'tempomail.fr', 'temporarily.de', 'temporario.com.br',
  'temporaryemail.net', 'temporaryforwarding.com', 'temporaryinbox.com', 'temporarymailaddress.com', 'tempsky.com',
  'temptation.to', 'tempymail.com', 'thanksnospam.info', 'thankyou2010.com', 'thc.st',
  'thelimestones.com', 'thietbivanphong4g.com', 'thisisnotmyrealemail.com', 'thismail.net', 'thismail.ru',
  'throam.com', 'throwam.com', 'throwaway.email', 'throwawaymail.com', 'tilien.com',
  'tittbit.in', 'tmailinator.com', 'tmail.ws', 'tmpeml.info', 'toiea.com',
  'tokenmail.de', 'toomail.biz', 'topranklist.de', 'tradermail.info', 'trash-amila.com',
  'trash-mail.at', 'trash-mail.com', 'trash-mail.de', 'trash2009.com', 'trashemail.de',
  'trashmail.at', 'trashmail.com', 'trashmail.de', 'trashmail.me', 'trashmail.net',
  'trashmail.org', 'trashmail.ws', 'trashmailer.com', 'trashymail.com', 'trashymail.net',
  'trbvm.com', 'trickmail.net', 'trillianpro.com', 'tryalert.com', 'turual.com',
  'twinmail.de', 'twoweirdtricks.com', 'tyldd.com', 'uggsrock.com', 'upliftnow.com',
  'uplipht.com', 'uroid.com', 'us.af', 'valemail.net', 'venompen.com',
  'veryrealemail.com', 'viditag.com', 'viewcastmedia.com', 'viewcastmedia.net', 'viewcastmedia.org',
  'viralplays.com', 'vkcode.ru', 'vpn.st', 'vsimcard.com', 'vubby.com',
  'wasteland.rfc822.org', 'webemail.me', 'webm4il.info', 'webuser.in', 'wee.my',
  'weg-werf-email.de', 'wegwerf-email-addressen.de', 'wegwerf-emails.de', 'wegwerfadresse.de', 'wegwerfemail.com',
  'wegwerfemail.de', 'wegwerfmail.de', 'wegwerfmail.info', 'wegwerfmail.net', 'wegwerfmail.org',
  'wetrainbayarea.com', 'wetrainbayarea.org', 'wh4f.org', 'whatiaas.com', 'whatpaas.com',
  'whopy.com', 'whyspam.me', 'willhackforfood.biz', 'willselfdestruct.com', 'winemaven.info',
  'wolfsmail.tk', 'writeme.us', 'wronghead.com', 'wuzup.net', 'wuzupmail.net',
  'wwwnew.eu', 'xagloo.com', 'xemaps.com', 'xents.com', 'xmaily.com',
  'xn--9kq967o.com', 'xoxy.net', 'yapped.net', 'yeah.net', 'yep.it',
  'yogamaven.com', 'yopmail.com', 'yopmail.fr', 'yopmail.gold', 'yopmail.net',
  'yordanmail.cf', 'you-spam.com', 'yourdomain.com', 'ypmail.webarnak.fr.eu.org', 'yuurok.com',
  'z1p.biz', 'zehnminuten.de', 'zehnminutenmail.de', 'zippymail.info', 'zoaxe.com',
  'zoemail.com', 'zoemail.net', 'zoemail.org', 'zomg.info', 'zxcv.com',
  'zxcvbnm.com', 'zzz.com'
];

// Suspicious login name patterns
export const SUSPICIOUS_LOGIN_PATTERNS = [
  /^admin\d*$/i,
  /^administrator$/i,
  /^root$/i,
  /^test\d*$/i,
  /^user\d*$/i,
  /^demo$/i,
  /^dev$/i,
  /^backup$/i,
  /^temp$/i,
  /^webmaster$/i,
  /^support$/i,
  /^sysadmin$/i,
  /^mysql$/i,
  /^postgres$/i,
  /^oracle$/i,
];

// WordPress roles
export const WP_ROLES = ['administrator', 'editor', 'author', 'contributor', 'subscriber'];
export const ADMIN_ROLES = ['administrator'];
