import * as fs from 'fs';
import * as path from 'path';
import { ScanResult } from './malware-scanner';
import { Vulnerability } from './vulnerability-scanner';
import { IntegrityResult } from './file-integrity';

export interface SmtpConfig {
  host: string;
  port: number;
  user: string;
  pass: string;
  from: string;
  to: string;
}

export interface EmailNotificationData {
  timestamp: string;
  scanPath: string;
  scanResult: ScanResult;
  vulnerabilities?: Vulnerability[];
  integrity?: IntegrityResult;
  subject?: string;
}

function getEnvConfig(): SmtpConfig {
  return {
    host: process.env.SMTP_HOST || 'localhost',
    port: parseInt(process.env.SMTP_PORT || '587', 10),
    user: process.env.SMTP_USER || '',
    pass: process.env.SMTP_PASS || '',
    from: process.env.SMTP_FROM || 'clean-sweep@localhost',
    to: process.env.SMTP_TO || '',
  };
}

function escapeShellArg(arg: string): string {
  return "'" + arg.replace(/'/g, "'\\''") + "'";
}

function generatePlainTextBody(data: EmailNotificationData): string {
  const lines: string[] = [];
  const status = data.scanResult.safe ? 'CLEAN' : 'THREATS DETECTED';

  lines.push('Clean Sweep Security Scan Report');
  lines.push('================================');
  lines.push('');
  lines.push(`Scan Path:    ${data.scanPath}`);
  lines.push(`Timestamp:    ${data.timestamp}`);
  lines.push(`Status:       ${status}`);
  lines.push(`Total Files:  ${data.scanResult.totalFiles}`);
  lines.push(`Threats:      ${data.scanResult.threats.length}`);
  lines.push('');

  if (data.scanResult.threats.length > 0) {
    lines.push('Threats Found:');
    lines.push('--------------');
    for (const threat of data.scanResult.threats) {
      const lineInfo = threat.line !== null ? `:${threat.line}` : '';
      lines.push(`  [${threat.type}] ${threat.file}${lineInfo}`);
      lines.push(`    Signature: ${threat.signature}`);
    }
    lines.push('');
  }

  if (data.vulnerabilities && data.vulnerabilities.length > 0) {
    lines.push('Known Vulnerabilities:');
    lines.push('----------------------');
    for (const vuln of data.vulnerabilities) {
      lines.push(`  ${vuln.component} ${vuln.version} - ${vuln.severity.toUpperCase()}`);
      lines.push(`    ${vuln.title} (${vuln.cve})`);
    }
    lines.push('');
  }

  if (data.integrity) {
    lines.push('File Integrity:');
    lines.push('---------------');
    if (data.integrity.wordpressVersion) {
      lines.push(`  WordPress Version: ${data.integrity.wordpressVersion}`);
    }
    lines.push(`  Files Checked: ${data.integrity.checked}`);
    lines.push(`  Modified:      ${data.integrity.modified}`);
    if (data.integrity.modifiedFiles.length > 0) {
      lines.push('  Modified Files:');
      for (const f of data.integrity.modifiedFiles) {
        lines.push(`    - ${f}`);
      }
    }
    lines.push('');
  }

  lines.push('--');
  lines.push('Generated by Clean Sweep CLI');

  return lines.join('\n');
}

export function generateDefaultSubject(data: EmailNotificationData): string {
  const status = data.scanResult.safe ? 'CLEAN' : 'THREATS DETECTED';
  const threatCount = data.scanResult.threats.length;
  return `[Clean Sweep] ${status} - ${data.scanPath} (${threatCount} threat${threatCount !== 1 ? 's' : ''})`;
}

export function generateEmailBody(data: EmailNotificationData): string {
  return generatePlainTextBody(data);
}

export function generateSendmailScript(data: EmailNotificationData, config?: SmtpConfig): string {
  const smtp = config || getEnvConfig();
  const subject = data.subject || generateDefaultSubject(data);
  const body = generatePlainTextBody(data);

  const lines: string[] = [];
  lines.push('#!/usr/bin/env bash');
  lines.push('# Auto-generated email notification script for Clean Sweep CLI');
  lines.push('# Generated: ' + data.timestamp);
  lines.push('');
  lines.push('set -euo pipefail');
  lines.push('');

  lines.push('SMTP_HOST=' + escapeShellArg(smtp.host));
  lines.push('SMTP_PORT=' + escapeShellArg(String(smtp.port)));
  lines.push('SMTP_USER=' + escapeShellArg(smtp.user));
  lines.push('SMTP_PASS=' + escapeShellArg(smtp.pass));
  lines.push('SMTP_FROM=' + escapeShellArg(smtp.from));
  lines.push('SMTP_TO=' + escapeShellArg(smtp.to));
  lines.push('');

  lines.push('# Check if required tools are available');
  lines.push('if command -v curl &> /dev/null; then');
  lines.push('  MAILER="curl"');
  lines.push('elif command -v sendmail &> /dev/null; then');
  lines.push('  MAILER="sendmail"');
  lines.push('elif command -v mail &> /dev/null; then');
  lines.push('  MAILER="mail"');
  lines.push('else');
  lines.push('  echo "Error: No mail utility found (curl, sendmail, or mail required)." >&2');
  lines.push('  exit 1');
  lines.push('fi');
  lines.push('');

  lines.push('# Build the email body');
  lines.push('EMAIL_BODY=$(cat <<\'BODY_EOF\'');
  lines.push(body);
  lines.push('BODY_EOF');
  lines.push(')');
  lines.push('');

  lines.push('echo "Sending email notification via ${MAILER}..."');
  lines.push('');

  lines.push('case "${MAILER}" in');
  lines.push('  curl)');
  lines.push('    curl --silent --show-error \\');
  lines.push('      --url "smtp://${SMTP_HOST}:${SMTP_PORT}" \\');
  lines.push('      --ssl-reqd \\');
  lines.push('      --user "${SMTP_USER}:${SMTP_PASS}" \\');
  lines.push('      --mail-from "${SMTP_FROM}" \\');
  lines.push('      --mail-rcpt "${SMTP_TO}" \\');
  lines.push('      --upload-file - <<EOF');
  lines.push('From: ${SMTP_FROM}');
  lines.push('To: ${SMTP_TO}');
  lines.push('Subject: ' + subject);
  lines.push('Content-Type: text/plain; charset=UTF-8');
  lines.push('');
  lines.push('${EMAIL_BODY}');
  lines.push('EOF');
  lines.push('    ;;');
  lines.push('  sendmail)');
  lines.push('    {');
  lines.push('      echo "From: ${SMTP_FROM}"');
  lines.push('      echo "To: ${SMTP_TO}"');
  lines.push('      echo "Subject: ' + subject + '"');
  lines.push('      echo "Content-Type: text/plain; charset=UTF-8"');
  lines.push('      echo ""');
  lines.push('      echo "${EMAIL_BODY}"');
  lines.push('    } | sendmail -t');
  lines.push('    ;;');
  lines.push('  mail)');
  lines.push('    echo "${EMAIL_BODY}" | mail -s "' + subject + '" "${SMTP_TO}"');
  lines.push('    ;;');
  lines.push('esac');
  lines.push('');
  lines.push('echo "Email notification sent successfully."');

  return lines.join('\n');
}

export function generateCurlOnlyScript(data: EmailNotificationData, config?: SmtpConfig): string {
  const smtp = config || getEnvConfig();
  const subject = data.subject || generateDefaultSubject(data);
  const body = generatePlainTextBody(data);

  const lines: string[] = [];
  lines.push('#!/usr/bin/env bash');
  lines.push('# Auto-generated curl-based email notification script for Clean Sweep CLI');
  lines.push('# Generated: ' + data.timestamp);
  lines.push('');
  lines.push('set -euo pipefail');
  lines.push('');

  lines.push('SMTP_HOST=${SMTP_HOST:-' + escapeShellArg(smtp.host) + '}');
  lines.push('SMTP_PORT=${SMTP_PORT:-' + escapeShellArg(String(smtp.port)) + '}');
  lines.push('SMTP_USER=${SMTP_USER:-' + escapeShellArg(smtp.user) + '}');
  lines.push('SMTP_PASS=${SMTP_PASS:-' + escapeShellArg(smtp.pass) + '}');
  lines.push('SMTP_FROM=${SMTP_FROM:-' + escapeShellArg(smtp.from) + '}');
  lines.push('SMTP_TO=${SMTP_TO:-' + escapeShellArg(smtp.to) + '}');
  lines.push('');

  lines.push('if ! command -v curl &> /dev/null; then');
  lines.push('  echo "Error: curl is required but not installed." >&2');
  lines.push('  exit 1');
  lines.push('fi');
  lines.push('');

  lines.push('curl --silent --show-error \\');
  lines.push('  --url "smtp://${SMTP_HOST}:${SMTP_PORT}" \\');
  lines.push('  --ssl-reqd \\');
  lines.push('  --user "${SMTP_USER}:${SMTP_PASS}" \\');
  lines.push('  --mail-from "${SMTP_FROM}" \\');
  lines.push('  --mail-rcpt "${SMTP_TO}" \\');
  lines.push('  --upload-file - <<EOF');
  lines.push('From: ${SMTP_FROM}');
  lines.push('To: ${SMTP_TO}');
  lines.push('Subject: ' + subject);
  lines.push('Content-Type: text/plain; charset=UTF-8');
  lines.push('');
  lines.push(body);
  lines.push('EOF');
  lines.push('');
  lines.push('echo "Email notification sent via curl."');

  return lines.join('\n');
}

export function generateEmailScript(
  data: EmailNotificationData,
  config?: SmtpConfig,
  mode: 'auto' | 'curl' = 'auto'
): string {
  if (mode === 'curl') {
    return generateCurlOnlyScript(data, config);
  }
  return generateSendmailScript(data, config);
}

export function getDefaultScriptPath(scanPath: string): string {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const safePath = scanPath.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 50);
  return path.join('reports', `email-${safePath}-${timestamp}.sh`);
}

export function saveEmailScript(script: string, filePath: string): void {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(filePath, script, 'utf-8');
  fs.chmodSync(filePath, 0o755);
}
